### PR TITLE
Change mutable listener with default init to rec value

### PR DESCRIPTION
**Pull request by CaringDev**
less mutability is always great, is it?

### CODE REVIEW

**Comment by tpetricek** [comment]
Does it work? If so, then I agree :)

I think some version of Fable had troubles with recursive values...

**Comment by CaringDev** [comment]
Good memory! I guess you refer to [Recursive values give "no enclosing entity" error](https://github.com/fable-compiler/Fable/issues/237) that was [fixed by disallowing recursive values](https://github.com/fable-compiler/Fable/blob/f83cc3b1bb3980ad9f019558b0756adcf39af947/src/fable/Fable.Client.Node/Main.fs#L86).
And indeed, without `#nowarn "40"`:

> [ERROR] F# project contains errors:
> Recursive value definitions are not supported (L35,47-L35,55) (.\3-drawing\client\helpers.fsx)

However, it seems to work now (with `nowarn` back in):

```javascript
var Async = function (__exports) {
  var AwaitDomEvent = __exports.AwaitDomEvent = function (el, event) {
    return fromContinuations(function (tupledArg) {
      var listener_2 = function listener_2() {
        return function (e) {
          el.removeEventListener(event, listener_1.value);
          tupledArg[0](e);
        };
      };

      var listener_1 = new Lazy(listener_2);
      var listener = listener_1.value;
      el.addEventListener(event, listener);
    });
  };

  return __exports;
}({});
```

@alfonsogarciacaro: does Fable now support recursive values in general? So we could maybe [remove the error generation](https://github.com/fable-compiler/Fable/compare/master...CaringDev:recursive_values)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @CaringDev for looking so deep into Fable code and Github history! 

As you point out, this should work. The case of https://github.com/fable-compiler/Fable/issues/237 was a bit different, but I've fixed the code to make it work so we can remove the warning :+1: https://github.com/fable-compiler/Fable/commit/eeedd69a1b1e96d52fad62bd94c62a067138c2cf

**Comment by CaringDev** [comment]
@tpetricek Good to merge, then 👍

**Comment by tpetricek** [comment]
Neat!

**Pull request merged**
